config/routes.rb
Rails.application.routes.draw do

   root 'status#home'
   get 'welcome' => 'status#home'
   
   get 'sensors' => 'sensors#home'
   get 'sensors/new' => 'sensors#new'
   post 'sensors' => 'sensors#create'
   get '/sensors/:id' => 'sensors#show', as: :sensor
   
   get '/signup' => 'users#new'
   resources :users
   
   get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy'

end

app/models/reading.rb
class Reading < ActiveRecord::Base

	belongs_to :sensor
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
	has_many :readings
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user 

  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end
  
  def require_user 
    redirect_to '/login' unless current_user 
  end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
	
	def home
		@sensors = Sensor.all
	end
	
	def new
	   @sensor = Sensor.new
	end

	def create
	  @sensor = Sensor.new(message_params)
	  if @sensor.save
		redirect_to '/sensors'
	  else
	    render 'new'
	  end
	end
	
	def show
		@sensor = Sensor.find(params[:id])
		@readings = @sensor.readings
	end
	
	
	private 
	def message_params
		params.require(:sensor).permit(:name, :tipus, :model) 
    end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new 
		
	end
	
	def create
		@user = User.find_by_device_name(params[:session][:device_name])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			redirect_to "/welcome"
		else
			redirect_to "login"
		end
	end
	
	def destroy 
		session[:user_id] = nil 
		redirect_to '/welcome' 
	end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
	
	before_action :require_user, only: [:home]

	def home
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to '/welcome'
		else
			redirect_to '/signup'
		end
	end
	
	private 
		def user_params
			params.require(:user).permit(:device_name, :password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="http://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css" rel="stylesheet" />
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,300' rel='stylesheet' type='text/css'>

  <title>HomeAuto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'defaults', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="header">
      <div class="container">
        <%= link_to root_path do %>
          <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1m.svg" width="80" height="80"> &#12501; &#65387; &#12488; &#12501; &#65387; &#12488;
        <% end %>

        <div class="nav pull-right">
        <% if current_user %> 
          <ul> 
            <li><%= current_user.device_name %> </li> 
            <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
          </ul> 
        <% else %> 
          <ul> 
            <li><%= link_to "Login", 'login' %></a></li> 
            <li><%= link_to "Signup", 'signup' %></a></li> 
          </ul> 
        <% end %>        
       </div>
      </div>
    </div>
      </div>
    </div>


<%= yield %>

</body>
</html>


    

app/views/sensors/home.html.erb
<div class="sensors">
  <div class="container">
    <h1>Sensors</h1>
  
  <% @sensors.each do |s| %> 
  <div class="sensor"> 
	  <p class="content"><%= s.id %></p> 
	  <p class="content"><%= s.name %></p> 
	  <p class="content"><%= s.tipus %></p> 
	  <p class="content"><%= s.model %></p> 
	  <p class="time"><%= s.created_at %></p> 
	</div> 
	<%= link_to "View Readings", sensor_path(s) %>
  <% end %>
  <br>
  <%= link_to 'New Sensor', "sensors/new" %>
  <br>
  <%= link_to 'Back', "/" %>

  </div>
</div>

app/views/sensors/new.html.erb
<div class="create">
  <div class="container">
  <div class="form">
    <h1>New Sensor</h1>
    
	<%= form_for(@sensor) do |f| %>  
	  <div class="field"> 
		<%= f.label :name %><%= f.text_field :name %><br> 
		<%= f.label :tipus %><%= f.text_field :tipus %><br> 
		<%= f.label :model %><%= f.text_field :model %>
	  </div> 
	  <div class="actions"> 
		<%= f.submit "Create" %> 
	  </div> 
	<% end %>
    <%= link_to 'Back', :action => "home" %>

    </div>
   
  </div>
</div>

app/views/sensors/show.html.erb
<div class="sensors">
  <div class="container">
      <h1>Readings</h1>

    <h2><%= @sensor.name %></h2>

    <div class="cards row">
      <% @readings.each do |r| %>
      <div class="card col-xs-10">
        <p><%= r.valor %></p>
		<p class="time"><%= r.created_at %></p><BR>
      </div>
      <% end %>
    </div>
    <%= link_to 'Back', :action => "home" %>
  </div>
</div>

app/views/status/home.html.erb
<div class="sensors">
  <div class="container">
<h1>Home Automation</h1>

  
  <%= link_to 'Sensors', "sensors" %>
</div>
</div>

app/views/users/new.html.erb
<div class="create">
  <div class="container">
		<div class="form">

		<h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
      <%= f.text_field :device_name, :placeholder => "Device name" %>
      <%= f.password_field :password, :placeholder => "Password" %>
  	  <div class="actions"> 
		<%= f.submit "Create an account"%>
	  </div>
    <% end %>
  
	</div>
  </div>
</div>